name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Clean and reinstall dependencies
        run: |
          pnpm install
          pnpm update

      - name: Deploy to NuxtHub pages
        uses: nuxt-hub/action@v2
        id: deploy-pages
        with:
          project-key: fietsersbond-ka-xqjv

      - name: Deploy to NuxtHub worker
        uses: nuxt-hub/action@v2
        id: deploy-worker
        with:
          project-key: fietsersbond-on-rb23
